name: Try Log Secrets

on:
  workflow_dispatch:
  
jobs:
  log:
    runs-on: ubuntu-latest
    
    steps:
      - name: Log the secret
        run: echo ${{ secrets.MY_SECRET}}
      - name: Testing secret 
        run: | 
            if  [ "$GEHEIM" == "Test" ] 
            then
              echo "Geheim is bekend"
            else
              echo "Geheim is onbekend"
            fi
        env:
          GEHEIM: ${{secrets.MY_SECRET}}
